TESTSET_ENABLE: False
OUTPUT_DIR: './work_dirs/mpii-efficient-b4'
RUN_EFFICIENT: False
MODEL:
  ARCH: "EFFNET"
  WEIGHT: './work_dirs/pretrained/efficientnet-b4.pth'
KEYPOINT:
  NUM: 16
  FLIP_PAIRS: [[0, 5], [1, 4], [2, 3], [10, 15], [11, 14], [12, 13]]
  UPPER_BODY_IDS: [7, 8, 9, 10, 11, 12, 13, 14, 15]
  LOWER_BODY_IDS: [0, 1, 2, 3, 4, 5, 6]
DATA:
  INPUT_SHAPE: (256, 256)
  OUTPUT_SHAPE: (64, 64)
  DATASET_NAME: "MPII"
  DATASET_ROOT: "datasets/mpii"
  BASIC_EXTENTION: 0.0
  RANDOM_EXTENTION: False
  X_EXTENTION: 0.25
  Y_EXTENTION: 0.25
  SCALE_SHRINK_RATIO: 1.0
  ROTATION_FACTOR: 60
  NUM_KEYPOINTS_HALF_BODY: 8
  PROB_HALF_BODY: 0.5
  Y_EXTENTION_HALF_BODY: 0.6
SOLVER:
  OPTIMIZER: 'Adam'
  IMS_PER_GPU: 32
  BASE_LR: 4e-3
  CHECKPOINT_PERIOD: 1600
  GAMMA: 0.5
  MAX_ITER: 28800
  SCHEDULER: 'linear'
  WARMUP_ITERS: 2400
TEST:
  IMS_PER_GPU: 32
  X_EXTENTION: 0.25
  Y_EXTENTION: 0.25
  GAUSSIAN_KERNEL: 9